# fly.toml app configuration file generated for newserver-depl on 2023-06-07T10:43:17+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "newserver-depl"
primary_region = "ams"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
